# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import enum
import typing

from nautilus_trader import model

__all__ = [
    "SODEX",
    "SODEX_PERPS",
    "SODEX_PERPS_VENUE",
    "SODEX_SPOT",
    "SODEX_SPOT_VENUE",
    "Market",
    "Network",
    "SodexDataClientConfig",
    "SodexDataClientFactory",
    "SodexExecClientConfig",
    "SodexExecutionClientFactory",
]

SODEX: str
SODEX_SPOT: str
SODEX_PERPS: str
SODEX_SPOT_VENUE: typing.Any
SODEX_PERPS_VENUE: typing.Any

@typing.final
class SodexDataClientConfig:
    def __init__(
        self,
        network: Network | None = None,
        market: Market | None = None,
        instrument_ids: typing.Sequence[model.InstrumentId] | None = None,
        update_instruments_interval_mins: int | None = None,
        timeout_secs: int | None = None,
    ) -> None: ...
    @property
    def network(self) -> Network: ...
    @property
    def market(self) -> Market: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def venue(self) -> str: ...

@typing.final
class SodexDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class SodexExecClientConfig:
    def __init__(
        self,
        network: Network | None = None,
        market: Market | None = None,
        account_id: int | None = None,
        api_key_name: str | None = None,
        api_private_key: str | None = None,
        wallet_address: str | None = None,
        update_instruments_interval_mins: int | None = None,
        timeout_secs: int | None = None,
    ) -> None: ...
    @property
    def network(self) -> Network: ...
    @property
    def market(self) -> Market: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def venue(self) -> str: ...
    def has_credentials(self) -> bool: ...

@typing.final
class SodexExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class Market(enum.Enum):
    SPOT = ...
    PERPS = ...

@typing.final
class Network(enum.Enum):
    MAINNET = ...
    TESTNET = ...
